baseURL = "http://mvp.yonsei.ac.kr"
languageCode = "en-us"
title = "Home"
theme = "kube"
description = "Image and Video Pattern Recogntion"
Paginate = 4
publishDir = "docs"
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Members"
    weight = 10
    url = "/members/"
[[menu.main]]
    name = "Research"
    weight = 20
    url = "/research/"
[[menu.main]]
    name = "Publications"
    weight = 25
    url = "/publications/"
[[menu.main]]
    name = "Projects"
    weight = 30
    url = "/projects/"
[[menu.main]]
    name = "Contact"
    weight = 40
    url = "/contact/"
